require 'rake'
require 'yaml'
require 'yajl'

desc "Run specs"
task "spec" => ["test:spec"]

desc "Run specs using SimpleCov"
task "spec:rcov" => ["test:spec:rcov"]

desc "Run ci using SimpleCov"
task "spec:ci" => ["test:spec:ci"]

namespace "bundler" do
  desc "Install gems"
  task "install" do
    sh("bundle install")
  end

  desc "Install gems for test"
  task "install:test" do
    sh("bundle install --without development production")
  end

  desc "Install gems for production"
  task "install:production" do
    sh("bundle install --without development test")
  end

  desc "Install gems for development"
  task "install:development" do
    sh("bundle install --without test production")
  end
end

namespace "vagrant" do
  desc "Setup /var/vcap paths"
  task :vcap_paths do
    %w[
      /var/vcap
      /var/vcap/store/postgresql_common/bin
      /var/vcap/store/postgresql_common/config
    ].each do |dir|
      sh "sudo mkdir -p #{dir}"
      sh "sudo chmod 775 #{dir}"
      sh "sudo chgrp admin -R #{dir}"
    end
  end

  desc "Copy common scripts into common warden folder"
  task :warden_scripts do
    templates_dir = File.expand_path("../../../jobs/postgresql_node/templates", __FILE__)
    common_dir = "/var/vcap/store/postgresql_common/bin"
    scripts = %w[warden_service_ctl pre_service_start.sh post_service_start.sh postgresql_ctl]
    scripts.each do |script|
      sh "sudo cp #{File.join(templates_dir, script)} #{common_dir}"
    end
  end
  
end
task :vagrant => ["vagrant:vcap_paths", "vagrant:warden_scripts"]

namespace "test" do
  def run_spec
    sh "nats-server &"
    Dir.chdir("spec"){ yield }
    sh "pkill -f nats-server"
  end

  task "spec" do |t|
    run_spec{ sh "rake spec" }
  end

  task "spec:rcov" do |t|
    run_spec{ sh "rake simcov" }
  end

  task "spec:ci" do |t|
    run_spec{ sh "rake spec:ci" }
  end
end
